// nyea-frontend/src/components/ui/button.tsx
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "../../lib/utils"

const buttonVariants = cva(
  "inline-flex items-center justify-center whitespace-nowrap rounded-xl text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 active:scale-95",
  {
    variants: {
      variant: {
        default: "bg-gradient-to-r from-blue-600 to-blue-700 text-white hover:from-blue-700 hover:to-blue-800 shadow-lg hover:shadow-xl",
        destructive: "bg-red-500 text-white hover:bg-red-600",
        outline: "border border-gray-200 bg-white hover:bg-gray-50 hover:border-gray-300",
        secondary: "bg-gray-100 text-gray-900 hover:bg-gray-200",
        ghost: "hover:bg-gray-100 hover:text-gray-900",
        link: "text-blue-600 underline-offset-4 hover:underline",
        apple: "bg-black text-white hover:bg-gray-800 shadow-lg hover:shadow-xl",
        primary: "bg-gradient-to-r from-[#9f162e] to-[#1f2444] text-white hover:from-[#1f2444] hover:to-[#9f162e] shadow-lg hover:shadow-xl",
        secondary_brand: "bg-[#1f2444] text-white hover:bg-[#9f162e] shadow-lg hover:shadow-xl transition-all duration-300",
        learn_more: "bg-[#1f2444] text-white hover:bg-[#9f162e] shadow-lg hover:shadow-xl transition-all duration-300",
        view_all: "bg-[#9f162e] text-white hover:bg-[#1f2444] shadow-lg hover:shadow-xl transition-all duration-300",
        transparent: "bg-transparent border border-white text-white hover:bg-white hover:text-[#1f2444] transition-all duration-300",
      },
      size: {
        default: "h-12 px-6 py-3",
        sm: "h-9 rounded-lg px-4 text-xs",
        lg: "h-10 md:h-12 lg:h-14 rounded-xl px-8 text-xs md:text-sm lg:text-md",
        icon: "h-10 w-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button"
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  }
)
Button.displayName = "Button"

export { Button, buttonVariants }

// nyea-backend/resources/js/Components/Button.vue
<script setup>
import { computed } from 'vue';
import LoadingSpinner from './LoadingSpinner.vue';

const props = defineProps({
    variant: {
        type: String,
        default: 'primary', // 'primary', 'secondary', 'danger', 'success', 'warning', 'ghost', 'link'
    },
    size: {
        type: String,
        default: 'md', // 'xs', 'sm', 'md', 'lg', 'xl'
    },
    disabled: {
        type: Boolean,
        default: false,
    },
    loading: {
        type: Boolean,
        default: false,
    },
    block: {
        type: Boolean,
        default: false,
    },
    rounded: {
        type: String,
        default: 'md', // 'none', 'sm', 'md', 'lg', 'full'
    },
    leftIcon: {
        type: String,
        default: null,
    },
    rightIcon: {
        type: String,
        default: null,
    },
    as: {
        type: String,
        default: 'button',
    },
    href: {
        type: String,
        default: null,
    },
    type: {
        type: String,
        default: 'button',
    },
});

const emit = defineEmits(['click']);

const isDisabled = computed(() => props.disabled || props.loading);

const baseClasses = 'inline-flex items-center justify-center font-medium transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2';

const variantClasses = computed(() => {
    const variants = {
        primary: 'bg-blue-600 hover:bg-blue-700 text-white border border-transparent focus:ring-blue-500',
        secondary: 'bg-gray-600 hover:bg-gray-700 text-white border border-transparent focus:ring-gray-500',
        danger: 'bg-red-600 hover:bg-red-700 text-white border border-transparent focus:ring-red-500',
        success: 'bg-green-600 hover:bg-green-700 text-white border border-transparent focus:ring-green-500',
        warning: 'bg-yellow-600 hover:bg-yellow-700 text-white border border-transparent focus:ring-yellow-500',
        ghost: 'bg-transparent hover:bg-gray-50 text-gray-700 border border-gray-300 focus:ring-gray-500',
        link: 'bg-transparent hover:bg-transparent text-blue-600 hover:text-blue-700 border-transparent focus:ring-blue-500 underline',
    };
    
    if (isDisabled.value) {
        return 'bg-gray-300 text-gray-500 border border-gray-300 cursor-not-allowed';
    }
    
    return variants[props.variant] || variants.primary;
});

const sizeClasses = computed(() => {
    const sizes = {
        xs: 'px-2.5 py-1.5 text-xs',
        sm: 'px-3 py-2 text-sm',
        md: 'px-4 py-2 text-sm',
        lg: 'px-4 py-2 text-base',
        xl: 'px-6 py-3 text-base',
    };
    
    return sizes[props.size] || sizes.md;
});

const roundedClasses = computed(() => {
    const rounded = {
        none: '',
        sm: 'rounded-sm',
        md: 'rounded-md',
        lg: 'rounded-lg',
        full: 'rounded-full',
    };
    
    return rounded[props.rounded] || rounded.md;
});

const blockClasses = computed(() => {
    return props.block ? 'w-full' : '';
});

const buttonClasses = computed(() => {
    return [
        baseClasses,
        variantClasses.value,
        sizeClasses.value,
        roundedClasses.value,
        blockClasses.value,
    ].join(' ');
});

const handleClick = (event) => {
    if (!isDisabled.value) {
        emit('click', event);
    }
};
</script>

<template>
    <component
        :is="as"
        :href="as === 'a' ? href : undefined"
        :type="as === 'button' ? type : undefined"
        :disabled="isDisabled"
        :class="buttonClasses"
        @click="handleClick"
    >
        <!-- Left Icon -->
        <svg
            v-if="leftIcon && !loading"
            :class="[
                'h-4 w-4',
                $slots.default ? (size === 'xs' ? 'mr-1' : 'mr-2') : ''
            ]"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
        >
            <path :d="leftIcon" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
        </svg>

        <!-- Loading Spinner -->
        <LoadingSpinner
            v-if="loading"
            :size="size === 'xs' ? 'sm' : 'sm'"
            :color="variant === 'ghost' || variant === 'link' ? 'gray' : 'white'"
            :class="$slots.default ? (size === 'xs' ? 'mr-1' : 'mr-2') : ''"
        />

        <!-- Content -->
        <slot />

        <!-- Right Icon -->
        <svg
            v-if="rightIcon && !loading"
            :class="[
                'h-4 w-4',
                $slots.default ? (size === 'xs' ? 'ml-1' : 'ml-2') : ''
            ]"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
        >
            <path :d="rightIcon" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
        </svg>
    </component>
</template>
